### ISSUE TITLE
Change: Div class backtocourse / To course redirection

### ISSUE THREAD

**Issue by gemguardian** [MFreakNL/moodle-block_vsf_module_navigation#3]
Hi Luuk,

Could you please change the re-direct of the div class Backtocourse / to course in a way that it is **not** redirecting to the **section** but to the **course overview page**

![2019-02-04_15-28-22](https://user-images.githubusercontent.com/16559999/52214322-a2e81b00-2891-11e9-835d-14a963425eee.jpg)

**Comment by luukverhoeven** [comment]
It should be redirecting without the _sectionid_ now. Could you please check if it's fixed in the latest version **2019020400**?

**Comment by gemguardian** [comment]
Hi Luuk,

Think it is the wrong line. The change is now redirecting the section name to the course, instead of the Back to course (Course name header).

It might be the course format setting that has an impact on the “Back to course” class.

You  can reproduce this issue by:


  *   Courseformat setting layout – Show all sections on one page
  *   Block setting – Display section name not activated
  *   Activities placed in section 1

Thank you
Gem

PS: we could do a call on Friday

Van: Luuk Verhoeven <notifications@github.com>
Verzonden: Monday, February 4, 2019 21:16
Aan: MFreakNL/moodle-block_vsf_module_navigation <moodle-block_vsf_module_navigation@noreply.github.com>
CC: Gemma Lesterhuis <gemma@ltnc.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [MFreakNL/moodle-block_vsf_module_navigation] Change: Div class backtocourse / To course redirection (#3)


It should be redirecting without the sectionid now. Could you please check if it's fixed in the latest version 2019020400?

**Comment by luukverhoeven** [comment]
Hi Gemma, 

Can please check if this issue still occurs in the latest version?

**Comment by gemguardian** [comment]
Hi Luuk,
Checked it worked 
Thank you again!
Gem

**Comment by luukverhoeven** [comment]
👍 you're welcome
